jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.REGISTRY }}/frontend-static:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: SSH to server & pull new image
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            docker pull ${{ secrets.REGISTRY }}/frontend-static:${{ github.sha }}
            docker stop frontend || true
            docker rm frontend  || true
            docker run -d --name frontend -p 80:80 ${{ secrets.REGISTRY }}/frontend-static:${{ github.sha }}
          EOF
